Proyecto.ISW712.PatronesDiseño/Controllers/RolCrudController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto.ISW712.PatronesDiseño.Helpers;
using Proyecto.ISW712.PatronesDiseño.Models;

namespace Proyecto.ISW712.PatronesDiseño.Controllers
{
    public class RolCrudController : Controller
    {
        private IConfiguration _configuration;
        public RolCrudController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            var singleton = Singleton.Singleton.Instance;//llama a la funcion singleton para sacar la sesion
            RolHelper factory = new RolHelper(singleton.Motores_bd[singleton.Bd_actual], _configuration["ConnectionStrings:" + singleton.Bd_actual]);//llama al helper de rol
            var Listrol = factory.GetRol();//saca la lista de rol, mediante el helper
            Console.WriteLine(_configuration["ConnectionStrings:" + singleton.Bd_actual]);
            ViewData["cadena1"] = singleton.Cadenas_conexion[singleton.Bd_actual];//pasa el nombre de la cedna de conexion en la sesion
            return View(Listrol);
        }
        public IActionResult AgregarRolView()
        {
            var singleton = Singleton.Singleton.Instance;//llama a la sesion
            ViewData["cadena1"] = singleton.Cadenas_conexion[singleton.Bd_actual];//saca la bd actual
            return View("AgregarRol");
        }
        public IActionResult Agregar(RolModel rol)//metodo de agregar rol
        {
            var singleton = Singleton.Singleton.Instance;//llama a la sesion
            RolHelper factory = new RolHelper(singleton.Motores_bd[singleton.Bd_actual], _configuration["ConnectionStrings:" + singleton.Bd_actual]);//llama al helper de rols
            factory.AgregarRol(rol);//del helper llama la funcion de agregar 

            return RedirectToAction("Index");//redireccion al index del rol
        }
        public IActionResult ModificarView(RolModel rol)//llama a la vista de rol y recibe por parametro al rol
        {
            var singleton = Singleton.Singleton.Instance;//llama a la sesion
            ViewData["cadena1"] = singleton.Cadenas_conexion[singleton.Bd_actual];//returna el nombre de la bd actual
            return View("ModificarView", rol);
        }
        public IActionResult Modificar(RolModel rol)//funcion de modificar
        {
            var singleton = Singleton.Singleton.Instance;//llama a la sesion
            RolHelper factory = new RolHelper(singleton.Motores_bd[singleton.Bd_actual], _configuration["ConnectionStrings:" + singleton.Bd_actual]);//llama al helper de rols
            factory.ModificarRol(rol);//modifica el rol
            return RedirectToAction("Index");//redireccion al index
        }
        public IActionResult Eliminar(int id)//metodo de eliminar
        {
            var singleton = Singleton.Singleton.Instance;//llama a la funcion singleton para sacar la sesion
            RolHelper factory = new RolHelper(singleton.Motores_bd[singleton.Bd_actual], _configuration["ConnectionStrings:" + singleton.Bd_actual]);//llama al helper de rols
            factory.DeleteRol(id);//elimina el rol por id
            return RedirectToAction("Index");//redireccion al index
        }
        public IActionResult DetalleView(RolModel rol)//vista de detalle
        {
            var singleton = Singleton.Singleton.Instance;//llama a la sesion
            ViewData["cadena1"] = singleton.Cadenas_conexion[singleton.Bd_actual]; //retuna la bd actual
            return View("DetalleView", rol);
        }

    }
}

Proyecto.ISW712.PatronesDiseño/Controllers/SingletonController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Proyecto.ISW712.PatronesDiseño.Controllers
{
    public class SingletonController : Controller
    {
        private IConfiguration _configuration;
        public SingletonController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            var singleton = Singleton.Singleton.Instance;
            Console.WriteLine(singleton.Cadenas_conexion[singleton.Bd_actual]);
            Console.WriteLine(singleton.Motores_bd[singleton.Bd_actual]);
            ViewData["CadenaConexion"] = singleton.Cadenas_conexion[singleton.Bd_actual];
            ViewData["MotorBD"] = singleton.Motores_bd[singleton.Bd_actual];
            var connectionStrings1 = _configuration["ConnectionStrings:db1"];
            var connectionStrings2 = _configuration["ConnectionStrings:db2"];
            var connectionStrings3 = _configuration["ConnectionStrings:db3"];
            ViewData["cadena1"] = connectionStrings1;
            ViewData["cadena2"] = connectionStrings2;
            ViewData["cadena3"] = connectionStrings3;
            //Console.WriteLine(connectionStrings1);
            //Console.WriteLine(connectionStrings2);
            //Console.WriteLine(connectionStrings3);

            return View();
        }
        [HttpPost]
        public IActionResult CambiarBD(string bd)
        {
            var singleton = Singleton.Singleton.Instance;
            singleton.Bd_actual = bd;
            return RedirectToAction("Index");
        }
    }
}

Proyecto.ISW712.PatronesDiseño/Controllers/UserCrudController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto.ISW712.PatronesDiseño.Data.FabricaUsuario;
using Proyecto.ISW712.PatronesDiseño.Helpers;
using Proyecto.ISW712.PatronesDiseño.Models;
using System.Data;
using System.Data.SqlClient;

namespace Proyecto.ISW712.PatronesDiseño.Controllers
{
    public class UserCrudController : Controller
    {
        private IConfiguration _configuration;
        public UserCrudController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()//vista principal
        {
            var singleton = Singleton.Singleton.Instance;//llama a la funcion singleton para sacar la sesion
            UsuarioHelper usuarioFactory = new UsuarioHelper(singleton.Motores_bd[singleton.Bd_actual], _configuration["ConnectionStrings:" + singleton.Bd_actual]);//llama al helper de usuarios
            var ListUsu = usuarioFactory.GetUsuario();//saca la lista de usuarios, mediante el helper
            Console.WriteLine(_configuration["ConnectionStrings:" + singleton.Bd_actual]);
            ViewData["cadena1"] = singleton.Cadenas_conexion[singleton.Bd_actual];//pasa el nombre de la cedna de conexion en la sesion
            return View(ListUsu);//retorna la vista y la lista de usuarios
        }
        public IActionResult Eliminar(int id)//metodo de eliminar
        {
            var singleton = Singleton.Singleton.Instance;//llama a la funcion singleton para sacar la sesion
            UsuarioHelper usuarioFactory = new UsuarioHelper(singleton.Motores_bd[singleton.Bd_actual], _configuration["ConnectionStrings:" + singleton.Bd_actual]);//llama al helper de usuarios
            usuarioFactory.DeleteUsuario(id);//elimina el usuario por id
            return RedirectToAction("Index");//redireccion al index
        }
        public IActionResult AgregarView()//vista de agregar usuarios
        {
            var singleton = Singleton.Singleton.Instance;//llama a la sesion
            ViewData["cadena1"] = singleton.Cadenas_conexion[singleton.Bd_actual];//saca la bd actual
            return View("Agregar");
        }
        public IActionResult Agregar(UsuarioModel usuario)//metodo de agregar usuario
        {
            var singleton = Singleton.Singleton.Instance;//llama a la sesion
            UsuarioHelper usuarioFactory = new UsuarioHelper(singleton.Motores_bd[singleton.Bd_actual], _configuration["ConnectionStrings:" + singleton.Bd_actual]);//llama al helper de usuarios
            usuarioFactory.AgregarUsuario(usuario);//del helper llama la funcion de agregar 

            return RedirectToAction("Index");//redireccion al index del usuario
        }
        public IActionResult ModificarView(UsuarioModel usuario)//llama a la vista de usuario y recibe por parametro al usuario
        {
            var singleton = Singleton.Singleton.Instance;//llama a la sesion
            ViewData["cadena1"] = singleton.Cadenas_conexion[singleton.Bd_actual];//returna el nombre de la bd actual
            return View("ModificarView", usuario);
        }
        public IActionResult Modificar(UsuarioModel usuario)//funcion de modificar
        {
            var singleton = Singleton.Singleton.Instance;//llama a la sesion
            UsuarioHelper usuarioFactory = new UsuarioHelper(singleton.Motores_bd[singleton.Bd_actual], _configuration["ConnectionStrings:" + singleton.Bd_actual]);//llama al helper de usuarios
            usuarioFactory.ModificarUsuario(usuario);//modifica el usuario
            return RedirectToAction("Index");//redireccion al index
        }
        public IActionResult DetalleView(UsuarioModel usuario)//vista de detalle
        {
            var singleton = Singleton.Singleton.Instance;//llama a la sesion
            ViewData["cadena1"] = singleton.Cadenas_conexion[singleton.Bd_actual]; //retuna la bd actual
            return View("DetalleView",usuario);
        }

    } 
}

Proyecto.ISW712.PatronesDiseño/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Patrones de Diseño</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proyecto.ISW712.PatronesDiseño.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Patrones de Diseño</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>           
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserCrud" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RolCrud" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Singleton" asp-action="Index">Configuracion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Proyecto.ISW712.PatronesDiseño - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>